spring:
    jpa:
        database: POSTGRESQL
        show-sql: false
        hibernate:
            ddl-auto: update
            dialect:  org.hibernate.dialect.PostgreSQL95Dialect
        properties.hibernate.temp.use_jdbc_metadata_defaults: false
    thymeleaf:
      mode: LEGACYHTML5
      cache: false
    liquibase:
      enabled: false
    datasource:
        platform: postgres
        url: jdbc:postgresql://localhost:5432/db
        username: postgres
        password: root
        driverClassName: org.postgresql.Driver
    mail:
      host: smtp.gmail.com
      port: 587
      username: d.borysov@infostroy.com.ua
      password: firstpostNINJA11
      properties.mail.smtp:
        auth: true
        starttls.enable: true



